import avatar from '/assets/avatar.svg'
export const specialistData = [{
    id: 1,
    img: avatar,
    name: "Dr. Jane",
    specialty: "Cardiologist",
    email: "email@p2doc.com",
    rate: '45.5/hr',
},
{
    id: 2,
    img: avatar,
    name: "Dr. Benson",
    specialty: "Urology",
    email: "email@p2doc.com",
    rate: '25.5/hr',
},
{
    id: 3,
    img: avatar,
    name: "Dr. Kate",
    specialty: "Neurology",
    email: "email@p2doc.com",
    rate: '20.5/hr',
},
{
    id: 4,
    img: avatar,
    name: "Dr. Stacy",
    specialty: "Dentist",
    email: "email@p2doc.com",
    rate: '15.5/hr',
},
{
    id: 5,
    img: avatar,
    name: "Dr. Miles",
    specialty: "Surgeon",
    email: "email@p2doc.com",
    rate: '50.5/hr',
},
{
    id: 6,
    img: avatar,
    name: "Dr. Grace",
    specialty: "Oncology",
    email: "email@p2doc.com",
    rate: '40.5/hr',
},
{
    id: 7,
    img: avatar,
    name: "Dr. George",
    specialty: "Psychiatry",
    email: "email@p2doc.com",
    rate: '24.5/hr',
},
{
    id: 8,
    img: avatar,
    name: "Dr. John Doe",
    specialty: "Dermatology",
    email: "email@p2doc.com",
    rate: '30.5/hr',
}
]